In [1]:
import pandas as pd

In [2]:
start_cd = 'all_data/wearable_data/Data/'

In [3]:
students = ['S'+str(i) for i in range(1,11)]

In [4]:
tests = ['Final', 'Midterm 1', 'Midterm 2']

In [5]:
ACC_df_prep = pd.DataFrame()
for s in students:
    for t in tests:
        df_paused = pd.read_csv(start_cd+s+'/'+t+'/ACC.csv')
        df_paused = df_paused.drop(0).reset_index().drop(columns=['index'])
        cols = df_paused.columns
        df_paused = df_paused.rename(columns={cols[0]:'x',cols[1]:'y',cols[-1]:'z'})
        df_paused['student'] = s
        df_paused['test'] = t
        ACC_df_prep = pd.concat([ACC_df_prep,df_paused])

ACC_df = ACC_df_prep
ACC_df.head()

     x     y    z student   test
0 -3.0  65.0  6.0      S1  Final
1 -3.0  65.0  6.0      S1  Final
2 -3.0  65.0  6.0      S1  Final
3 -3.0  65.0  6.0      S1  Final
4 -3.0  65.0  6.0      S1  Final

In [82]:
BVP_df_prep = pd.DataFrame()
for s in students:
    for t in tests:
        df_paused = pd.read_csv(start_cd+s+'/'+t+'/BVP.csv')
        df_paused = df_paused.drop(0).reset_index().drop(columns=['index'])
        cols = df_paused.columns
        df_paused = df_paused.rename(columns={cols[0]:'data'})
        df_paused['student'] = s
        df_paused['test'] = t
        BVP_df_prep = pd.concat([BVP_df_prep,df_paused])

BVP_df = BVP_df_prep
BVP_df

        data student       test
0      -0.00      S1      Final
1      -0.00      S1      Final
2      -0.00      S1      Final
3      -0.00      S1      Final
4      -0.00      S1      Final
...      ...     ...        ...
831485  2.30     S10  Midterm 2
831486  2.12     S10  Midterm 2
831487  1.89     S10  Midterm 2
831488  1.59     S10  Midterm 2
831489  1.11     S10  Midterm 2

[28370518 rows x 3 columns]

In [83]:
BVP_df_m1 = BVP_df[BVP_df['test'] == 'Midterm 1'].drop(columns=['test'])
BVP_df_m2 = BVP_df[BVP_df['test'] == 'Midterm 2']
BVP_df_fi = BVP_df[BVP_df['test'] == 'Final']

In [58]:
BVP_df_m1['row'] = BVP_df_m1.groupby('student').cumcount()

In [65]:
BVP_df_m1_pivot = BVP_df_m1.pivot(index='row', columns='student', values='data')
BVP_df_m1_pivot.reset_index(drop=True, inplace=True)
BVP_df_m1_pivot

student   S1  S10   S2   S3   S4   S5   S6   S7   S8    S9
0       -0.0 -0.0 -0.0 -0.0 -0.0 -0.0 -0.0 -0.0 -0.0 -0.00
1       -0.0 -0.0 -0.0 -0.0 -0.0 -0.0 -0.0 -0.0 -0.0 -0.00
2       -0.0 -0.0 -0.0 -0.0 -0.0 -0.0 -0.0 -0.0 -0.0 -0.00
3       -0.0 -0.0 -0.0 -0.0 -0.0 -0.0 -0.0 -0.0 -0.0 -0.00
4       -0.0 -0.0 -0.0 -0.0 -0.0 -0.0 -0.0 -0.0 -0.0 -0.00
...      ...  ...  ...  ...  ...  ...  ...  ...  ...   ...
811619   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  2.06
811620   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  1.88
811621   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  1.69
811622   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  1.46
811623   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  1.19

[811624 rows x 10 columns]

In [66]:
BVP_df_m2['row'] = BVP_df_m2.groupby('student').cumcount()

/var/folders/y6/yynhnkp53m70dw4wkft15lbw0000gn/T/ipykernel_37723/3452171853.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  BVP_df_m2['row'] = BVP_df_m2.groupby('student').cumcount()

In [67]:
BVP_df_m2_pivot = BVP_df_m2.pivot(index='row', columns='student', values='data')
BVP_df_m2_pivot.reset_index(drop=True, inplace=True)
BVP_df_m2_pivot

student   S1  S10   S2   S3   S4   S5    S6   S7   S8   S9
0       -0.0 -0.0 -0.0 -0.0 -0.0 -0.0 -0.00 -0.0 -0.0 -0.0
1       -0.0 -0.0 -0.0 -0.0 -0.0 -0.0 -0.00 -0.0 -0.0 -0.0
2       -0.0 -0.0 -0.0 -0.0 -0.0 -0.0 -0.00 -0.0 -0.0 -0.0
3       -0.0 -0.0 -0.0 -0.0 -0.0 -0.0 -0.00 -0.0 -0.0 -0.0
4       -0.0 -0.0 -0.0 -0.0 -0.0 -0.0 -0.00 -0.0 -0.0 -0.0
...      ...  ...  ...  ...  ...  ...   ...  ...  ...  ...
908155   NaN  NaN  NaN  NaN  NaN  NaN -2.28  NaN  NaN  NaN
908156   NaN  NaN  NaN  NaN  NaN  NaN -2.02  NaN  NaN  NaN
908157   NaN  NaN  NaN  NaN  NaN  NaN -1.83  NaN  NaN  NaN
908158   NaN  NaN  NaN  NaN  NaN  NaN -1.81  NaN  NaN  NaN
908159   NaN  NaN  NaN  NaN  NaN  NaN -1.98  NaN  NaN  NaN

[908160 rows x 10 columns]

In [68]:
BVP_df_fi['row'] = BVP_df_fi.groupby('student').cumcount()

/var/folders/y6/yynhnkp53m70dw4wkft15lbw0000gn/T/ipykernel_37723/3260387420.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  BVP_df_fi['row'] = BVP_df_fi.groupby('student').cumcount()

In [69]:
BVP_df_fi_pivot = BVP_df_fi.pivot(index='row', columns='student', values='data')
BVP_df_fi_pivot.reset_index(drop=True, inplace=True)
BVP_df_fi_pivot

student   S1  S10   S2    S3   S4   S5   S6   S7   S8   S9
0       -0.0 -0.0 -0.0 -0.00 -0.0 -0.0 -0.0 -0.0 -0.0 -0.0
1       -0.0 -0.0 -0.0 -0.00 -0.0 -0.0 -0.0 -0.0 -0.0 -0.0
2       -0.0 -0.0 -0.0 -0.00 -0.0 -0.0 -0.0 -0.0 -0.0 -0.0
3       -0.0 -0.0 -0.0 -0.00 -0.0 -0.0 -0.0 -0.0 -0.0 -0.0
4       -0.0 -0.0 -0.0 -0.00 -0.0 -0.0 -0.0 -0.0 -0.0 -0.0
...      ...  ...  ...   ...  ...  ...  ...  ...  ...  ...
1652602  NaN  NaN  NaN  0.33  NaN  NaN  NaN  NaN  NaN  NaN
1652603  NaN  NaN  NaN  0.42  NaN  NaN  NaN  NaN  NaN  NaN
1652604  NaN  NaN  NaN  0.98  NaN  NaN  NaN  NaN  NaN  NaN
1652605  NaN  NaN  NaN  1.81  NaN  NaN  NaN  NaN  NaN  NaN
1652606  NaN  NaN  NaN  2.62  NaN  NaN  NaN  NaN  NaN  NaN

[1652607 rows x 10 columns]

In [78]:
EDA_df_prep = pd.DataFrame()
for s in students:
    for t in tests:
        df_paused = pd.read_csv(start_cd+s+'/'+t+'/EDA.csv')
        df_paused = df_paused.drop(0).reset_index().drop(columns=['index'])
        cols = df_paused.columns
        df_paused = df_paused.rename(columns={cols[0]:'data'})
        df_paused['student'] = s
        df_paused['test'] = t
        EDA_df_prep = pd.concat([EDA_df_prep,df_paused])

EDA_df = EDA_df_prep
EDA_df.head()

       data student   test
0  0.000000      S1  Final
1  0.005125      S1  Final
2  0.020501      S1  Final
3  0.021783      S1  Final
4  0.023064      S1  Final

In [6]:
HR_df_prep = pd.DataFrame()
for s in students:
    for t in tests:
        df_paused = pd.read_csv(start_cd+s+'/'+t+'/HR.csv')
        df_paused = df_paused.drop(0).reset_index().drop(columns=['index'])
        cols = df_paused.columns
        df_paused = df_paused.rename(columns={cols[0]:'data'})
        df_paused['student'] = s
        df_paused['test'] = t
        HR_df_prep = pd.concat([HR_df_prep,df_paused])

HR_df = HR_df_prep
HR_df

         data student       test
0      116.00      S1      Final
1       82.50      S1      Final
2       96.33      S1      Final
3       86.25      S1      Final
4       98.60      S1      Final
...       ...     ...        ...
12977  115.07     S10  Midterm 2
12978  116.13     S10  Midterm 2
12979  116.07     S10  Midterm 2
12980  116.47     S10  Midterm 2
12981  116.42     S10  Midterm 2

[443002 rows x 3 columns]

In [15]:
# HR_df['data'] = HR_df['data'].astype(float)

In [16]:
# HR_df.to_csv('HR_df.csv',index=False)

In [9]:
IBI_df_prep = pd.DataFrame()
for s in students:
    for t in tests:
        df_paused = pd.read_csv(start_cd+s+'/'+t+'/IBI.csv')
        cols = df_paused.columns
        df_paused = df_paused.rename(columns={cols[0]:'time', cols[1]:'dt'})
        df_paused['student'] = s
        df_paused['test'] = t
        IBI_df_prep = pd.concat([IBI_df_prep,df_paused])

IBI_df = IBI_df_prep
IBI_df.head()

         time        dt student   test
0   84.847634  0.468771      S1  Final
1   85.347657  0.500023      S1  Final
2   85.722674  0.375017      S1  Final
3  107.754932  0.437520      S1  Final
4  108.223704  0.468771      S1  Final

In [5]:
TEMP_df_prep = pd.DataFrame()
for s in students:
    for t in tests:
        df_paused = pd.read_csv(start_cd+s+'/'+t+'/TEMP.csv')
        df_paused = df_paused.drop(0).reset_index().drop(columns=['index'])
        cols = df_paused.columns
        df_paused = df_paused.rename(columns={cols[0]:'temp'})
        df_paused['student'] = s
        df_paused['test'] = t
        TEMP_df_prep = pd.concat([TEMP_df_prep,df_paused])

TEMP_df = TEMP_df_prep
TEMP_df['test'].unique()

array(['Final', 'Midterm 1', 'Midterm 2'], dtype=object)

In [7]:
TEMP_df.to_csv("TEMP_df.csv")

In [19]:
grades_df = pd.DataFrame({
    'Midterm 1' : {'S1' : 78/100, 'S2': 82/100, 'S3': 77/100, 'S4': 75/100, 'S5': 67/100, 'S6': 71/100, 'S7': 64/100, 'S8': 92/100, 'S9': 80/100, 'S10': 89/100},
    'Midterm 2' : {'S1' : 82/100, 'S2': 85/100, 'S3': 90/100, 'S4': 77/100, 'S5': 77/100, 'S6': 64/100, 'S7': 33/100, 'S8': 88/100, 'S9': 39/100, 'S10': 64/100},
    'Final' : {'S1' : 182/200, 'S2': 180/200, 'S3': 188/200, 'S4': 149/200, 'S5': 157/200, 'S6': 175/200, 'S7': 110/200, 'S8': 184/200, 'S9': 126/200, 'S10': 116/200}
})
grades_df = round(grades_df, 2)